apiVersion: batch/v1
kind: CronJob
metadata:
  name: dev-db-backup
  namespace: database
spec:
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 3
  schedule: "01 00 * * *" # Setiap hari pada pukul 00:00
  jobTemplate:
    spec:
      template:
        spec:
          nodeName: kvm4
          containers:
            - name: dev-db-backup
              image: postgres:17.6-alpine3.22
              env:
                - name: PGHOST
                  value: postgres
                - name: PGUSER
                  valueFrom:
                    secretKeyRef:
                      name: kasecrets
                      key: db_username
                - name: PGPASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: kasecrets
                      key: db_password
                - name: PGDATABASE
                  value: dev
              volumeMounts:
                - name: host-backup
                  mountPath: /backup
              command:
                - /bin/bash
                - -c
                - >
                  TIMESTAMP=$(date +%Y%m%d) &&
                  pg_dump -Fc "$PGDATABASE" > /backup/backup_${PGDATABASE}_$TIMESTAMP.dump &&
                  echo "Backup tersimpan di /backup/backup_${PGDATABASE}_$TIMESTAMP.dump" &&
                  find /backup -name "backup_${PGDATABASE}_*.dump" -type f -mtime +30 -exec rm -f {} \; &&
                  echo "File backup lebih dari 30 hari telah dihapus."
          restartPolicy: OnFailure
          volumes:
            - name: host-backup
              hostPath:
                path: /opt/pgsql_backups
                type: DirectoryOrCreate
